---

# When deploying an EDC, there are various configuration parameters that should not be part of the configuration file.
# To not serve a bad example, this demo will set some settings using secrets as well. In a productive environment this secrets would probably be deployed independently.

{{- $plato_psql_password := .Values.platopostgresql.auth.password -}}
{{- $plato_api_auth_key := "password" -}}
{{- $plato_vault_token := .Values.platovault.server.dev.devRootToken -}}
{{- $sokrates_psql_password := .Values.sokratespostgresql.auth.password -}}
{{- $sokrates_api_auth_key := "password" -}}
{{- $sokrates_vault_token := .Values.sokratesvault.server.dev.devRootToken -}}

---

apiVersion: v1
kind: Secret
metadata:
  name: aio-plato-control-secret
  namespace: {{ .Release.Namespace | default "default" | quote }}
  labels:
    {{- include "aio.labels" . | nindent 4 }}
type: Opaque
stringData:
  # see extension https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/tree/main/extensions/api/auth-tokenbased
  EDC_API_AUTH_KEY: {{ $plato_api_auth_key | toString | quote }}
  # see extension https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/tree/main/extensions/sql/asset-index-sql
  EDC_DATASOURCE_ASSET_PASSWORD: {{ $plato_psql_password | toString | quote }}
  # see extension https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/tree/main/extensions/sql/contract-definition-store-sql
  EDC_DATASOURCE_CONTRACTDEFINITION_PASSWORD: {{ $plato_psql_password | toString | quote }}
  # see extension https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/tree/main/extensions/sql/contract-negotiation-store-sql
  EDC_DATASOURCE_CONTRACTNEGOTIATION_PASSWORD: {{ $plato_psql_password | toString | quote }}
  # see extension https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/tree/main/extensions/sql/policy-store-sql
  EDC_DATASOURCE_POLICY_PASSWORD: {{ $plato_psql_password | toString | quote }}
  # see extension https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/tree/main/extensions/sql/transfer-process-store-sql
  EDC_DATASOURCE_TRANSFERPROCESS_PASSWORD: {{ $plato_psql_password | toString | quote }}
  # see extension https://github.com/catenax-ng/product-edc/tree/develop/edc-extensions/hashicorp-vault
  EDC_VAULT_HASHICORP_TOKEN: {{ $plato_vault_token | toString | quote }}

---

apiVersion: v1
kind: Secret
metadata:
  name: aio-plato-data-secret
  namespace: {{ .Release.Namespace | default "default" | quote }}
  labels:
    {{- include "aio.labels" . | nindent 4 }}
type: Opaque
stringData:
  # see extension https://github.com/catenax-ng/product-edc/tree/develop/edc-extensions/hashicorp-vault
  EDC_VAULT_HASHICORP_TOKEN: {{ $plato_vault_token | toString | quote }}

---

apiVersion: v1
kind: Secret
metadata:
  name: aio-sokrates-control-secret
  namespace: {{ .Release.Namespace | default "default" | quote }}
  labels:
    {{- include "aio.labels" . | nindent 4 }}
type: Opaque
stringData:
  # see extension https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/tree/main/extensions/api/auth-tokenbased
  EDC_API_AUTH_KEY: {{ $sokrates_api_auth_key | toString | quote }}
  # see extension https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/tree/main/extensions/sql/asset-index-sql
  EDC_DATASOURCE_ASSET_PASSWORD: {{ $sokrates_psql_password | toString | quote }}
  # see extension https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/tree/main/extensions/sql/contract-definition-store-sql
  EDC_DATASOURCE_CONTRACTDEFINITION_PASSWORD: {{ $sokrates_psql_password | toString | quote }}
  # see extension https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/tree/main/extensions/sql/contract-negotiation-store-sql
  EDC_DATASOURCE_CONTRACTNEGOTIATION_PASSWORD: {{ $sokrates_psql_password | toString | quote }}
  # see extension https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/tree/main/extensions/sql/policy-store-sql
  EDC_DATASOURCE_POLICY_PASSWORD: {{ $sokrates_psql_password | toString | quote }}
  # see extension https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/tree/main/extensions/sql/transfer-process-store-sql
  EDC_DATASOURCE_TRANSFERPROCESS_PASSWORD: {{ $sokrates_psql_password | toString | quote }}
  # see extension https://github.com/catenax-ng/product-edc/tree/develop/edc-extensions/hashicorp-vault
  EDC_VAULT_HASHICORP_TOKEN: {{ $sokrates_vault_token | toString | quote }}

---

apiVersion: v1
kind: Secret
metadata:
  name: aio-sokrates-data-secret
  namespace: {{ .Release.Namespace | default "default" | quote }}
  labels:
    {{- include "aio.labels" . | nindent 4 }}
type: Opaque
stringData:
  # see extension https://github.com/catenax-ng/product-edc/tree/develop/edc-extensions/hashicorp-vault
  EDC_VAULT_HASHICORP_TOKEN: {{ $sokrates_vault_token | toString | quote }}
