apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "edc-dataplane.fullname" . }}-configmap
  labels:
    {{- include "edc-dataplane.labels" . | nindent 4 }}
data:
  configuration.properties: |-
    {{- range $k, $v := .Values.configuration.properties }}
    {{- if $v }}
    {{ $k | replace "_" "." }}={{ $v }}
    {{- else }}
    # {{ $k | replace "_" "." }}=
    {{- end }}
    {{- end }}
  opentelemetry.properties: |-
    {{- range $k, $v := .Values.opentelemetry.properties }}
    {{- if $v }}
    {{ $k | replace "_" "." }}={{ $v }}
    {{- else }}
    # {{ $k | replace "_" "." }}=
    {{- end }}
    {{- end }}
  logging.properties: |-
    {{- range $k, $v := .Values.logging.properties }}
    {{- if $v }}
    {{ $k | replace "_" "." }}={{ $v }}
    {{- else }}
    # {{ $k | replace "_" "." }}=
    {{- end }}
    {{- end }}