---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "edc-dataplane.fullname" . }}
  namespace: {{ .Release.Namespace | default "default" | quote }}
  labels:
    {{- include "edc-dataplane.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "edc-dataplane.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/env-config: {{ include (print $.Template.BasePath "/configmap-env.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "edc-dataplane.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.imagePullSecret.dockerconfigjson }}
      imagePullSecrets:
        - name: {{ include "edc-dataplane.fullname" . }}-imagepullsecret
      {{- else }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      serviceAccountName: {{ include "edc-dataplane.serviceAccountName" . }}
      automountServiceAccountToken: {{ if .Values.automountServiceAccountToken }}true{{ else }}false{{ end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: default
              containerPort: {{ .Values.edc.endpoints.default.port }}
              protocol: TCP
            - name: public
              containerPort: {{ .Values.edc.endpoints.public.port }}
              protocol: TCP
            - name: control
              containerPort: {{ .Values.edc.endpoints.control.port }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.edc.endpoints.metrics.port }}
              protocol: TCP
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.edc.endpoints.default.path }}/check/liveness
              port: default
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.edc.endpoints.default.path }}/check/readiness
              port: default
          {{- end }}
          {{- if .Values.startupProbe.enabled }}
          startupProbe:
            httpGet:
              path: {{ .Values.edc.endpoints.default.path }}/check/startup
              port: default
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.startupProbe.initialDelaySeconds }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "edc-dataplane.fullname" . }}-env
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: configuration
              mountPath: /app/configuration.properties
              subPath: configuration.properties
            - name: configuration
              mountPath: /app/opentelemetry.properties
              subPath: opentelemetry.properties
            - name: configuration
              mountPath: /app/logging.properties
              subPath: logging.properties
      volumes:
        - name: configuration
          configMap:
            name: {{ include "edc-dataplane.fullname" . }}-configmap
            items:
              - key: configuration.properties
                path: configuration.properties
              - key: opentelemetry.properties
                path: opentelemetry.properties
              - key: logging.properties
                path: logging.properties
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
