{{- $fullName := include "edc-dataplane.fullname" . }}
{{- $labels := include "edc-dataplane.labels" . | nindent 4 }}
{{- $gitVersion := .Capabilities.KubeVersion.GitVersion }}
{{- $edcEndpoints := .Values.edc.endpoints }}
{{- $namespace := .Release.Namespace }}
{{- range .Values.ingresses }}
{{- if and .enabled .endpoints }}
{{- $ingressName := printf "%s-%s" $fullName .hostname }}
---
{{- if semverCompare ">=1.19-0" $gitVersion }}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" $gitVersion }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $ingressName }}
  namespace: {{ $namespace | default "default" | quote }}
  labels:
    {{- $labels | nindent 2 }}
  annotations:
    {{- if and .className (not (semverCompare ">=1.18-0" $gitVersion)) }}
    {{- if not (hasKey .annotations "kubernetes.io/ingress.class") }}
    {{- $_ := set .annotations "kubernetes.io/ingress.class" .className}}
    {{- end }}
    {{- end }}
    {{- if .certManager }}
    {{- if .certManager.issuer }}
    {{- $_ := set .annotations "cert-manager.io/issuer" .certManager.issuer}}
    {{- end }}
    {{- if .certManager.clusterIssuer }}
    {{- $_ := set .annotations "cert-manager.io/cluster-issuer" .certManager.clusterIssuer}}
    {{- end }}
    {{- end }}
    {{- with .annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if and .className (semverCompare ">=1.18-0" $gitVersion) }}
  ingressClassName: {{ .className }}
  {{- end }}
  {{- if .hostname }}
  {{- if .tls }}
  tls:
    - hosts:
        - {{ .hostname }}
      secretName: {{ $ingressName }}-tls
  {{- end }}
  rules:
    - host: {{ .hostname }}
      http:
        paths:
          {{- $ingressEdcEndpoints := .endpoints }}
          {{- range  $name, $mapping := $edcEndpoints }}
          {{- if (has $name $ingressEdcEndpoints) }}
          - path: {{ $mapping.path }}
            pathType: Prefix
            backend:
              {{- if semverCompare ">=1.19-0" $gitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $mapping.port }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $mapping.port }}
              {{- end }}
        {{- end }}
  {{- end }}
  {{- end }}
{{- end }}{{- /* end: if .enabled */}}
{{- end }}{{- /* end: range .Values.ingresses */}}
