#################################################################################
#  Copyright (c) 2021,2024 Contributors to the Eclipse Foundation
#  Copyright (c) 2025 Cofinity-X GmbH
#
#  See the NOTICE file(s) distributed with this work for additional
#  information regarding copyright ownership.
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License, Version 2.0 which is available at
#  https://www.apache.org/licenses/LICENSE-2.0.
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations
#  under the License.
#
#  SPDX-License-Identifier: Apache-2.0
#  Assisted-By: Claude-Opus-4.8
#################################################################################


---
version: 2
updates:

  # Gradle
  -
    package-ecosystem: "gradle"
    target-branch: main
    directory: /
    labels:
      - "dependabot"
      - "dependencies"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 50
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: "org.eclipse.dataspacetck.*"
    groups:
      test-dependencies:
        patterns:
          - "org.junit*"
          - "org.mockito*"
          - "org.assertj*"
          - "org.awaitility*"
          - "org.testcontainers*"
          - "com.github.dasniko:testcontainers-keycloak"
          - "io.rest-assured*"
          - "org.wiremock*"
          - "io.qameta.allure*"
      build-tooling:
        patterns:
          - "com.bmuschko*"
          - "com.gradleup*"
          - "io.swagger*"
          - "com.diffplug.spotless*"
          - "org.sonarqube*"
          - "com.github.ben-manes*"
          - "org.jreleaser*"
      logging:
        patterns:
          - "org.apache.logging.log4j*"
          - "org.slf4j*"
          - "ch.qos.logback*"
          - "io.opentelemetry*"
      serialization-and-crypto:
        patterns:
          - "com.fasterxml.jackson*"
          - "jakarta.json*"
          - "jakarta.ws.rs*"
          - "com.apicatalog*"
          - "com.networknt*"
          - "org.bouncycastle*"
          - "com.nimbusds*"
      cloud-sdks:
        patterns:
          - "software.amazon.awssdk*"
          - "com.azure*"
      database:
        patterns:
          - "org.postgresql*"
          - "org.flywaydb*"

  # Github Actions
  -
    package-ecosystem: "github-actions"
    target-branch: main
    directories:
      - "/"                         # scan workflows
      - "/.github/actions/*"        # scan all composite actions’ action.yml
    labels:
      - "dependabot"
      - "github-actions"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 50
    cooldown:
      default-days: 7
    groups:
      github-actions-all:
        patterns:
          - "*"

  # Docker
  - package-ecosystem: "docker"
    target-branch: main
    directories:
      - "resources"
      - "edc-extensions/bdrs-client/src/test/resources"
      - "edc-tests/e2e-fixtures/src/testFixtures/resources"
    labels:
      - "dependabot"
      - "docker"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 50
    cooldown:
      default-days: 7
    groups:
      docker-base-images:
        patterns:
          - "*"
