---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "txdc.fullname" . }}-controlplane
  namespace: {{ .Release.Namespace | default "default" | quote }}
  labels:
    {{- include "txdc.controlplane.labels" . | nindent 4 }}
data:
  opentelemetry.properties: |-
    {{- .Values.controlplane.opentelemetry | nindent 4 }}

  logging.properties: |-
    {{- .Values.controlplane.logging | nindent 4 }}
