{{- if .Values.controlplane.autoscaling.enabled }}
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "txdc.fullname" . }}-controlplane
  labels:
    {{- include "txdc.controlplane.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "txdc.fullname" . }}-controlplane
  minReplicas: {{ .Values.controlplane.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.controlplane.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.controlplane.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.controlplane.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.controlplane.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.controlplane.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
