apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "omejdn.fullname" . }}
  labels:
    {{- include "omejdn.labels" . | nindent 4 }}
data:
  scope_mapping.yml: |-
    ---
    idsc:IDS_CONNECTOR_ATTRIBUTES_ALL:
    - referringConnector

  omejdn.yml:  |-
    ---
    host: http://ids-daps:4567/
    path_prefix: ''
    bind_to: 0.0.0.0
    allow_origin: "*"
    app_env: debug
    openid: false
    user_backend:
      - yaml
    user_backend_default: yaml
    accept_audience: idsc:IDS_CONNECTORS_ALL
    issuer: http://ids-daps:4567/
    environment: development
    default_audience:
      - idsc:IDS_CONNECTORS_ALL
    access_token:
      expiration: 3600
      algorithm: RS256
    id_token:
      expiration: 3600
      algorithm: RS256

  plugins.yml: |-
    ---
    plugins:
      token_user_attributes:

  clients.yml: |-
      ---
      - client_id: data-plane-oauth2
        client_secret: supersecret
        name: provision oauth2
        grant_types:
          - client_credentials
        token_endpoint_auth_method: client_secret_post
        scope: openid
{{- range $i, $val := .Values.connectors }}
      - client_id: {{ quote $val.id }}
        name: {{ quote $val.name }}
        token_endpoint_auth_method: private_key_jwt
        grant_types:
        - client_credentials
        scope:
        - idsc:IDS_CONNECTOR_ATTRIBUTES_ALL
        attributes:
        - key: idsc
          value: IDS_CONNECTOR_ATTRIBUTES_ALL
        - key: securityProfile
          value: idsc:BASE_SECURITY_PROFILE
        {{- range $key, $value := $val.attributes }}
        - key: {{ $key }}
          value: {{ $value }}
        {{- end }}
        redirect_uri: http://localhost:4200
{{ end -}}


{{- range $i, $val :=  .Values.connectors }}
  {{ $val.name }}: {{ quote $val.certificate | toString }}
{{ end -}}
