#
#  Copyright (c) 2023 Bayerische Motoren Werke Aktiengesellschaft (BMW AG)
#  Copyright (c) 2021, 2023 Contributors to the Eclipse Foundation
#
#  See the NOTICE file(s) distributed with this work for additional
#  information regarding copyright ownership.
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License, Version 2.0 which is available at
#  https://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations
#  under the License.
#
#  SPDX-License-Identifier: Apache-2.0
#

## This file can be used to verify that the chart is working properly. It provides an exemplary configuration
## that is intended to be used with the supporting infrastructure.
## 1. install DAPS:
##  helm install infrastructure edc-tests/deployment/src/main/resources/helm/test-infrastructure \                                                                                                                 ─╯
##    --wait-for-jobs
##
## 2. install in-mem runtime. Note that the key and crt must match exactly the DAPS setup, c.f. edc-tests/deployment/src/main/resources/helm/test-infrastructure/values.yaml
##  export DAPSKEY="<private-key-content>"
##  export DAPSCRT="<certificate-content>"
##  export YOUR_VAULT_SECRETS="daps-key:$DAPSKEY;daps-crt:$DAPSCRT"
##  helm install trudy charts/tractusx-connector-memory -f edc-tests/deployment/src/main/resources/helm/tractusx-connector-memory-test.yaml --set vault.secrets=$YOUR_VAULT_SECRETS

---
fullnameOverride: tx-inmem
participant:
  id: "test-participant"
runtime:
  service:
    type: NodePort
  endpoints:
    management:
      authKey: password
  ssi:
    miw:
      url: "http://localhost:8080"
      authorityId: "authorityId"
  image:
    pullPolicy: Never
    tag: "latest"
    repository: "edc-runtime-memory"
  securityContext:
    # avoids some errors in the log: cannot write temp files of large multipart requests when R/O
    readOnlyRootFilesystem: false
vault:
  secretNames:
    transferProxyTokenEncryptionAesKey: aes-keys
  # this must be set through CLI args: --set vault.secrets=$YOUR_VAULT_SECRETS where YOUR_VAULT_SECRETS should
  # be a string in the format "key1:secret1;key2:secret2;..."
  secrets:
  server:
    postStart:
      - sh
      - -c
      - |-
        {
        sleep 5

        /bin/vault kv put secret/client-secret content=4bDC8/uXB6o517zqqCdrPA==

        /bin/vault kv put secret/aes-keys content=YWVzX2VuY2tleV90ZXN0Cg==
        }
backendService:
  httpProxyTokenReceiverUrl: "http://backend:8080"
tests:
  hookDeletePolicy: before-hook-creation
