@startuml

!define sokratesColor 66CCFF
!define platoColor CCFF99
!define dapsColor FFFF99

node PlatoSetup as "Plato Connector Setup" {
    database PlatoPsql as "PostgreSQL" #platoColor
    database PlatoKeyVault as "HashiCorp Vault" #platoColor
    component PlatoConnector as "Eclipse Dataspace Connector" {
        artifact PlatoControlPlane as "Control Plane" #platoColor
        artifact PlatoDataPlane as "Data Plane" #platoColor
    }
    component PlatoBackendService as "Backend Application" #platoColor
}

PlatoControlPlane -- PlatoPsql
PlatoControlPlane -- PlatoKeyVault
PlatoDataPlane -- PlatoKeyVault
PlatoDataPlane -left- PlatoControlPlane
PlatoControlPlane -left- PlatoBackendService

node SokratesSetup as "Sokrates Connector Setup" {
    database SokratesPsql as "PostgreSQL" #sokratesColor
    database SokratesKeyVault as "HashiCorp Vault" #sokratesColor
    component SokratesConnector as "Eclipse Dataspace Connector" {
        artifact SokratesControlPlane as "Control Plane" #sokratesColor
        artifact SokratesDataPlane as "Data Plane" #sokratesColor
    }
    component SokratesBackendService as "Backend Application" #sokratesColor
}

SokratesControlPlane -- SokratesPsql
SokratesControlPlane -- SokratesKeyVault
SokratesDataPlane -- SokratesKeyVault
SokratesDataPlane -left- SokratesControlPlane
SokratesControlPlane -left- SokratesBackendService


node IdentityProvider as "Identity Provider" {
    component OmejdnDaps as "Omejdn DAPS" #dapsColor
}

PlatoPsql -[hidden]down- OmejdnDaps
SokratesControlPlane -[hidden]up- OmejdnDaps

@enduml
