---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "edc-controlplane.fullname" . }}-configmap
  namespace: {{ .Release.Namespace | default "default" | quote }}
  labels:
    {{- include "edc-controlplane.labels" . | nindent 4 }}
data:
  configuration.properties: |-
    web.http.default.port={{ .Values.edc.endpoints.default.port }}
    web.http.default.path={{ .Values.edc.endpoints.default.path }}
    web.http.data.port={{ .Values.edc.endpoints.data.port }}
    web.http.data.path={{ .Values.edc.endpoints.data.path }}
    web.http.validation.port={{ .Values.edc.endpoints.validation.port }}
    web.http.validation.path={{ .Values.edc.endpoints.validation.path }}
    web.http.control.port={{ .Values.edc.endpoints.control.port }}
    web.http.control.path={{ .Values.edc.endpoints.control.path }}
    web.http.ids.port={{ .Values.edc.endpoints.ids.port }}
    web.http.ids.path={{ .Values.edc.endpoints.ids.path }}
    {{- .Values.configuration.properties | nindent 4 }}

  opentelemetry.properties: |-
    {{- .Values.opentelemetry.properties | nindent 4 }}

  logging.properties: |-
    {{- .Values.logging.properties | nindent 4 }}
