/********************************************************************************
 * Copyright (c) 2023 Bayerische Motoren Werke Aktiengesellschaft (BMW AG)
 * Copyright (c) 2021,2023 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Apache License, Version 2.0 which is available at
 * https://www.apache.org/licenses/LICENSE-2.0.
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ********************************************************************************/
// Some portions generated by Claude Code

package org.eclipse.tractusx.edc.provision.additionalheaders;

import org.eclipse.edc.connector.dataplane.http.spi.HttpDataAddress;
import org.eclipse.edc.connector.dataplane.spi.provision.ProvisionResource;
import org.eclipse.edc.connector.dataplane.spi.provision.ProvisionedResource;
import org.eclipse.edc.connector.dataplane.spi.provision.Provisioner;
import org.eclipse.edc.spi.response.StatusResult;

import java.util.concurrent.CompletableFuture;

import static org.eclipse.edc.dataaddress.httpdata.spi.HttpDataAddressSchema.HTTP_DATA_TYPE;
import static org.eclipse.tractusx.edc.edr.spi.CoreConstants.AGREEMENT_ID_PROPERTY;
import static org.eclipse.tractusx.edc.edr.spi.CoreConstants.BPN_PROPERTY;

public class AdditionalHeadersProvisioner implements Provisioner {

    @Override
    public String supportedType() {
        return HTTP_DATA_TYPE;
    }

    @Override
    public CompletableFuture<StatusResult<ProvisionedResource>> provision(ProvisionResource resource) {
        var address = HttpDataAddress.Builder.newInstance()
                .copyFrom(resource.getDataAddress())
                .addAdditionalHeader("Edc-Contract-Agreement-Id", (String) resource.getProperty(AGREEMENT_ID_PROPERTY))
                .addAdditionalHeader("Edc-Bpn", (String) resource.getProperty(BPN_PROPERTY))
                .build();

        var provisioned = ProvisionedResource.Builder.from(resource)
                .dataAddress(address)
                .build();

        return CompletableFuture.completedFuture(StatusResult.success(provisioned));
    }
}
