/********************************************************************************
 * Copyright (c) 2023 Bayerische Motoren Werke Aktiengesellschaft (BMW AG)
 * Copyright (c) 2021,2023 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Apache License, Version 2.0 which is available at
 * https://www.apache.org/licenses/LICENSE-2.0.
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ********************************************************************************/
// Some portions generated by Claude Code

package org.eclipse.tractusx.edc.provision.additionalheaders;

import org.eclipse.edc.connector.dataplane.spi.DataFlow;
import org.eclipse.edc.connector.dataplane.spi.provision.ProvisionResource;
import org.eclipse.edc.connector.dataplane.spi.provision.ResourceDefinitionGenerator;
import org.jetbrains.annotations.Nullable;

import static org.eclipse.edc.dataaddress.httpdata.spi.HttpDataAddressSchema.HTTP_DATA_TYPE;
import static org.eclipse.tractusx.edc.edr.spi.CoreConstants.AGREEMENT_ID_PROPERTY;
import static org.eclipse.tractusx.edc.edr.spi.CoreConstants.BPN_PROPERTY;

class AdditionalHeadersResourceDefinitionGenerator implements ResourceDefinitionGenerator {

    AdditionalHeadersResourceDefinitionGenerator(String type) {
        this.type = type;
    }

    private final String type;

    @Override
    public String supportedType() {
        return type;
    }

    @Override
    public @Nullable ProvisionResource generate(DataFlow dataFlow) {
        return ProvisionResource.Builder.newInstance()
                .flowId(dataFlow.getId())
                .type(HTTP_DATA_TYPE)
                .dataAddress(dataFlow.getSource())
                .property(AGREEMENT_ID_PROPERTY, dataFlow.getAgreementId())
                .property(BPN_PROPERTY, dataFlow.getProperties().get(BPN_PROPERTY))
                .build();
    }
}
