---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "txdc.fullname" . }}-dataplane
  namespace: {{ .Release.Namespace | default "default" | quote }}
  labels:
    {{- include "txdc.dataplane.labels" . | nindent 4 }}
data:
  opentelemetry.properties: |-
    {{- .Values.dataplane.opentelemetry | nindent 4 }}

  logging.properties: |-
    {{- .Values.dataplane.logging | nindent 4 }}
