/********************************************************************************
 * Copyright (c) 2023 Bayerische Motoren Werke Aktiengesellschaft (BMW AG)
 * Copyright (c) 2021,2023 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Apache License, Version 2.0 which is available at
 * https://www.apache.org/licenses/LICENSE-2.0.
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ********************************************************************************/
// Some portions generated by Claude Code

package org.eclipse.tractusx.edc.provision.additionalheaders;

import org.eclipse.edc.connector.dataplane.http.spi.HttpDataAddress;
import org.eclipse.edc.connector.dataplane.spi.DataFlow;
import org.eclipse.edc.connector.dataplane.spi.provision.ProvisionResource;
import org.junit.jupiter.api.Test;

import java.util.Map;

import static org.assertj.core.api.AssertionsForClassTypes.assertThat;
import static org.assertj.core.api.InstanceOfAssertFactories.type;
import static org.eclipse.tractusx.edc.edr.spi.CoreConstants.AGREEMENT_ID_PROPERTY;
import static org.eclipse.tractusx.edc.edr.spi.CoreConstants.BPN_PROPERTY;

class AdditionalHeadersResourceDefinitionGeneratorTest {

    private final AdditionalHeadersResourceDefinitionGenerator generator = new AdditionalHeadersResourceDefinitionGenerator("HttpData");

    @Test
    void supportedType_shouldReturnHttpData() {
        assertThat(generator.supportedType()).isEqualTo("HttpData");
    }

    @Test
    void shouldCreateResourceDefinitionWithDataAddressAndProperties() {
        var source = HttpDataAddress.Builder.newInstance().baseUrl("http://any").build();
        var dataFlow = DataFlow.Builder.newInstance()
                .id("flowId")
                .source(source)
                .properties(Map.of(BPN_PROPERTY, "bpn", AGREEMENT_ID_PROPERTY, "contractId"))
                .build();

        var result = generator.generate(dataFlow);

        assertThat(result)
                .asInstanceOf(type(ProvisionResource.class))
                .satisfies(resource -> {
                    assertThat(resource.getFlowId()).isEqualTo("flowId");
                    assertThat(resource.getType()).isEqualTo("HttpData");
                    assertThat(resource.getDataAddress()).isNotNull();
                    assertThat(resource.getProperty("contractId")).isEqualTo("contractId");
                    assertThat(resource.getProperty("bpn")).isEqualTo("bpn");
                });
    }
}
