/********************************************************************************
 * Copyright (c) 2023 Bayerische Motoren Werke Aktiengesellschaft (BMW AG)
 * Copyright (c) 2021,2023 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Apache License, Version 2.0 which is available at
 * https://www.apache.org/licenses/LICENSE-2.0.
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ********************************************************************************/
// Some portions generated by Claude Code

package org.eclipse.tractusx.edc.provision.additionalheaders;

import org.eclipse.edc.connector.dataplane.spi.provision.ProvisionerManager;
import org.eclipse.edc.connector.dataplane.spi.provision.ResourceDefinitionGeneratorManager;
import org.eclipse.edc.junit.extensions.DependencyInjectionExtension;
import org.eclipse.edc.spi.system.ServiceExtensionContext;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

import static org.mockito.ArgumentMatchers.isA;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;

@ExtendWith(DependencyInjectionExtension.class)
class ProvisionAdditionalHeadersExtensionTest {

    private final ResourceDefinitionGeneratorManager resourceDefinitionGeneratorManager = mock();
    private final ProvisionerManager provisionerManager = mock();

    @BeforeEach
    void setUp(ServiceExtensionContext context) {
        context.registerService(ResourceDefinitionGeneratorManager.class, resourceDefinitionGeneratorManager);
        context.registerService(ProvisionerManager.class, provisionerManager);
    }

    @Test
    void initializeShouldRegisterGeneratorAndProvisioners(ProvisionAdditionalHeadersExtension extension, ServiceExtensionContext context) {
        extension.initialize(context);

        verify(resourceDefinitionGeneratorManager, times(2)).registerProviderGenerator(isA(AdditionalHeadersResourceDefinitionGenerator.class));
        verify(provisionerManager).register(isA(AdditionalHeadersProvisioner.class));
        verify(provisionerManager).register(isA(AdditionalHeadersDeprovisioner.class));
    }
}
