name: "Generate DEPENDENCIES file and publish to GitHub pages"
description: "Generate DEPENDENCIES file using Eclipse Dash Tool and publish result to the GitHub pages"

inputs:
  run:
    description: how the dependencies check must applied. "standard" will fail only for 'rejected' deps, "strict" will fail also for 'restricted' ones
    required: false
    default: standard

runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup-java
    - name: Download latest Eclipse Dash
      shell: bash
      run: |
        curl -L https://repo.eclipse.org/service/local/artifact/maven/redirect\?r\=dash-licenses\&g\=org.eclipse.dash\&a\=org.eclipse.dash.licenses\&v\=LATEST --output dash.jar
    - name: Generate DEPENDENCIES
      shell: bash
      run: |
        ./gradlew allDependencies | grep -Poh "(?<=\s)[\w.-]+:[\w.-]+:[^:\s\[\]]+" | sort | uniq | java -jar dash.jar - -summary DEPENDENCIES || true
        ./gradlew allDependencies | grep -Poh "(?<=\s)[\w.-]+:[\w.-]+:[^:\s\[\]]+" | sort | uniq > dependency-list
        
         if ! [ -s DEPENDENCIES ];
          then
            echo "error: DEPENDENCIES file was not created correctly, likely because Dash didn't work correctly. Please trigger the workflow again";
            exit 1;
          fi
    - name: evaluate DEPENDENCIES
      shell: bash
      run: |
        grep "restricted" DEPENDENCIES || true > RESTRICTED;
        if [ -s RESTRICTED ];
        then
          if [[ "${{ inputs.run }}" == "strict" ]];
          then
            echo "error: restricted dependencies found:";
            cat RESTRICTED;
            exit 1;
          else
            echo "warning: restricted dependencies found:";
            cat RESTRICTED;
          fi
        fi
        
        rm RESTRICTED || true

        grep "rejected" DEPENDENCIES || true > REJECTED;
        if [ -s REJECTED ];
        then
          echo "error: rejected dependencies found:";
          cat REJECTED;
          exit 1;
        fi
        
        rm REJECTED || true

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: public
        keep_files: true
