apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "edc-controlplane.fullname" . }}-configmap
  labels:
    {{- include "edc-controlplane.labels" . | nindent 4 }}
data:
  configuration.properties: |-
    {{ .Values.configuration.properties | nindent 4 }}
