openapi: 3.0.1
paths:
  /adapter/asset/sync/{assetId}:
    get:
      operationId: getAssetSynchronous
      parameters:
      - in: path
        name: assetId
        required: true
        schema:
          type: string
          example: null
      - in: query
        name: providerUrl
        schema:
          type: string
          example: null
      - in: query
        name: contractAgreementId
        schema:
          type: string
          example: null
      - in: query
        name: contractAgreementReuse
        schema:
          type: boolean
          default: true
          example: null
      - in: query
        name: timeout
        schema:
          type: string
          example: null
      responses:
        default:
          content:
            application/json: {}
          description: default response
      tags:
      - Control Plane Adapter
