openapi: 3.0.1
paths:
  /adapter/open_transfer:
    post:
      description: Initiates a contract negotiation and a transfer process for a given
        offer and with the given counter part. Please note that successfully invoking
        this endpoint only means that the negotiation was initiated.
      operationId: openTransfer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferOpenRequestDto'
      responses:
        "200":
          description: The negotiation was successfully initiated.
        "400":
          content:
            application/json:
              schema:
                type: array
                example: null
                items:
                  $ref: '#/components/schemas/ApiErrorDetail'
          description: Request body was malformed
      tags:
      - Control Plane Adapter Api
components:
  schemas:
    Action:
      type: object
      example: null
      properties:
        constraint:
          $ref: '#/components/schemas/Constraint'
        includedIn:
          type: string
          example: null
        type:
          type: string
          example: null
    ApiErrorDetail:
      type: object
      example: null
      properties:
        invalidValue:
          type: string
          example: null
        message:
          type: string
          example: null
        path:
          type: string
          example: null
        type:
          type: string
          example: null
    CallbackAddressDto:
      type: object
      example: null
      properties:
        events:
          type: array
          example: null
          items:
            type: string
            example: null
          uniqueItems: true
        transactional:
          type: boolean
          example: null
        uri:
          type: string
          example: null
      required:
      - events
      - uri
    Constraint:
      type: object
      discriminator:
        propertyName: edctype
      example: null
      properties:
        edctype:
          type: string
          example: null
      required:
      - edctype
    ContractOfferDescription:
      type: object
      example: null
      properties:
        assetId:
          type: string
          example: null
        offerId:
          type: string
          example: null
        policy:
          $ref: '#/components/schemas/Policy'
        validity:
          type: integer
          format: int64
          example: null
      required:
      - assetId
      - offerId
      - policy
    Duty:
      type: object
      example: null
      properties:
        action:
          $ref: '#/components/schemas/Action'
        assignee:
          type: string
          example: null
        assigner:
          type: string
          example: null
        consequence:
          $ref: '#/components/schemas/Duty'
        constraints:
          type: array
          example: null
          items:
            $ref: '#/components/schemas/Constraint'
        parentPermission:
          $ref: '#/components/schemas/Permission'
        target:
          type: string
          example: null
        uid:
          type: string
          example: null
    Permission:
      type: object
      example: null
      properties:
        action:
          $ref: '#/components/schemas/Action'
        assignee:
          type: string
          example: null
        assigner:
          type: string
          example: null
        constraints:
          type: array
          example: null
          items:
            $ref: '#/components/schemas/Constraint'
        duties:
          type: array
          example: null
          items:
            $ref: '#/components/schemas/Duty'
        target:
          type: string
          example: null
        uid:
          type: string
          example: null
    Policy:
      type: object
      example: null
      properties:
        '@type':
          type: string
          enum:
          - SET
          - OFFER
          - CONTRACT
          example: null
        assignee:
          type: string
          example: null
        assigner:
          type: string
          example: null
        extensibleProperties:
          type: object
          additionalProperties:
            type: object
            example: null
          example: null
        inheritsFrom:
          type: string
          example: null
        obligations:
          type: array
          example: null
          items:
            $ref: '#/components/schemas/Duty'
        permissions:
          type: array
          example: null
          items:
            $ref: '#/components/schemas/Permission'
        prohibitions:
          type: array
          example: null
          items:
            $ref: '#/components/schemas/Prohibition'
        target:
          type: string
          example: null
    Prohibition:
      type: object
      example: null
      properties:
        action:
          $ref: '#/components/schemas/Action'
        assignee:
          type: string
          example: null
        assigner:
          type: string
          example: null
        constraints:
          type: array
          example: null
          items:
            $ref: '#/components/schemas/Constraint'
        target:
          type: string
          example: null
        uid:
          type: string
          example: null
    TransferOpenRequestDto:
      type: object
      example: null
      properties:
        callbackAddresses:
          type: array
          example: null
          items:
            $ref: '#/components/schemas/CallbackAddressDto'
        connectorAddress:
          type: string
          example: null
        connectorId:
          type: string
          example: null
        consumerId:
          type: string
          example: null
        offer:
          $ref: '#/components/schemas/ContractOfferDescription'
        offerId:
          $ref: '#/components/schemas/ContractOfferDescription'
        protocol:
          type: string
          example: null
        providerId:
          type: string
          example: null
      required:
      - connectorAddress
      - connectorId
      - offer
      - protocol
