---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend-application.fullname" . }}
  labels:
    {{- include "backend-application.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "backend-application.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "backend-application.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "backend-application.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{ if .Values.image.command -}}
          command:
            {{ toYaml .Values.image.command | nindent 12 }}
          {{ end -}}
          {{ if .Values.livenessProbe -}}
          livenessProbe:
            {{ toYaml .Values.livenessProbe | nindent 12 }}
          {{ end -}}
          {{ if .Values.readinessProbe -}}
          readinessProbe:
            {{ toYaml .Values.readinessProbe | nindent 12 }}
          {{ end -}}
          volumeMounts:
            - name: configmap
              mountPath: {{ .Values.script.path }}
              subPath: handler.sh
            - name: data
              mountPath: /tmp/data
          env:
            - name: TCP_SERVER_SCRIPT_PATH
              value: {{ .Values.script.path | quote }}
            - name: TCP_SERVER_PORT
              value: {{ .Values.container.port | quote}}
          ports:
            - containerPort: {{ .Values.container.port }}
              protocol: TCP
              name: http
      volumes:
        - name: configmap
          configMap:
            name: {{ include "backend-application.fullname" . }}
            items:
              - key: handler.sh
                path: handler.sh
            defaultMode: 0744
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "backend-application.fullname" . }}-pvc
          {{ else }}
          emptyDir:
            {}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
