{{ if .Values.persistence.enabled -}}
---
apiVersion: "v1"
kind: PersistentVolumeClaim
metadata:
  name: {{ include "backend-application.fullname" . }}-pvc
  labels:
    {{- include "backend-application.labels" . | nindent 4 }}
spec:
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
  {{- end }}
  accessModes:
    {{- if .Values.persistence.accessMode }}
    - {{ .Values.persistence.accessMode | quote }}
    {{ else }}
    {{- if .Values.autoscaling.enabled }}
    - ReadWriteMany
    {{ else }}
    - ReadWriteOnce
    {{- end }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.capacity | quote }}
{{ end -}}
