@startuml

!define aliceColor 66CCFF
!define bobColor CCFF99
!define dapsColor FFFF99

node PlatoSetup as "Plato Connector Setup" {
    database PlatoPsql as "PostgreSQL" #bobColor
    database PlatoKeyVault as "HashiCorp Vault" #bobColor
    component PlatoConnector as "Eclipse Dataspace Connector" {
        artifact BobControlPlane as "Control Plane" #bobColor
        artifact BobDataPlane as "Data Plane" #bobColor
    }
    component PlatoBackendService as "Backend Application" #bobColor
}

BobControlPlane -- PlatoPsql
BobControlPlane -- PlatoKeyVault
BobDataPlane -- PlatoKeyVault
BobDataPlane -left- BobControlPlane
BobControlPlane -left- PlatoBackendService

node SokratesSetup as "Sokrates Connector Setup" {
    database SokratesPsql as "PostgreSQL" #aliceColor
    database SokratesKeyVault as "HashiCorp Vault" #aliceColor
    component SokratesConnector as "Eclipse Dataspace Connector" {
        artifact AliceControlPlane as "Control Plane" #aliceColor
        artifact AliceDataPlane as "Data Plane" #aliceColor
    }
    component AliceBackendService as "Backend Application" #aliceColor
}

AliceControlPlane -- SokratesPsql
AliceControlPlane -- SokratesKeyVault
AliceDataPlane -- SokratesKeyVault
AliceDataPlane -left- AliceControlPlane
AliceControlPlane -left- AliceBackendService


node IdentityProvider as "Identity Provider" {
    component OmejdnDaps as "Omejdn DAPS" #dapsColor
}

PlatoPsql -[hidden]down- OmejdnDaps
AliceControlPlane -[hidden]up- OmejdnDaps

@enduml
