name: "Publish Docker Image"
description: "Build and publish a Docker Image to DockerHub"
inputs:
  rootDir:
    required: true
    description: "The directory where the notice.md file and the src/main/docker directory are located"
  namespace:
    required: false
    default: "tractusx"
    description: "The Docker image namespace"
  imagename:
    required: true
    description: "the name of the image"
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    #####################
    # Login to DockerHub
    #####################
    - name: DockerHub login
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    ###############################
    # Set metadata of docker image
    ###############################
    # Create SemVer or ref tags dependent of trigger event
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ inputs.namespace }}/${{ inputs.imagename }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}
          type=semver,pattern={{major}}.{{minor}}

    ###############################
    # Build and push the image
    ###############################
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ${{ inputs.rootDir }}/src/main/docker/Dockerfile
        build-args: |
          JAR=${{ inputs.rootDir }}/build/libs/${{ inputs.imagename }}.jar
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    ###############################
    # Update the description
    # https://github.com/peter-evans/dockerhub-description
    ###############################
    - name: Update Docker Hub description
      if: github.event_name != 'pull_request' && ${{ secrets.DOCKER_HUB_USER }} && ${{ secrets.DOCKER_HUB_TOKEN }}
      uses: peter-evans/dockerhub-description@v3
      with:
        readme-filepath: ${{ inputs.rootDir }}/notice.md
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        repository: ${{ inputs.namespace }}/${{ inputs.imagename }}