#################################################################################
#  Copyright (c) 2023 Mercedes-Benz Tech Innovation GmbH
#  Copyright (c) 2021,2023 Contributors to the Eclipse Foundation
#
#  See the NOTICE file(s) distributed with this work for additional
#  information regarding copyright ownership.
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License, Version 2.0 which is available at
#  https://www.apache.org/licenses/LICENSE-2.0.
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations
#  under the License.
#
#  SPDX-License-Identifier: Apache-2.0
#################################################################################

---
name: "Deployment Tests"

on:
  workflow_call:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  test-prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Cache ContainerD Image Layers
        uses: actions/cache@v4
        with:
          path: /var/lib/containerd/io.containerd.snapshotter.v1.overlayfs
          key: ${{ runner.os }}-io.containerd.snapshotter.v1.overlayfs

  test-in-memory:
    runs-on: ubuntu-latest
    needs: test-prepare
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/run-deployment-test
        name: "Run deployment test using KinD and Helm"
        with:
          imagename: edc-runtime-memory
          rootDir: edc-controlplane/edc-runtime-memory
          helm_command: |-
            helm install tx-inmem charts/tractusx-connector-memory \
            -f edc-tests/deployment/src/main/resources/helm/tractusx-connector-memory-test.yaml \
            --wait-for-jobs --timeout=120s --dependency-update
            
            # wait for the pod to become ready
            kubectl rollout status deployment tx-inmem
            
            # execute the helm test
            helm test tx-inmem

  test-hashicorp-postgres:
    runs-on: ubuntu-latest
    needs: test-prepare
    strategy:
      fail-fast: false
      # this will verify that the official distribution of the Tractus-X EDC Helm chart runs on the last 3 Kubernetes versions
      matrix:
        k8s-version: [ "v1.31.0",
                       "v1.30.4",
                       "v1.29.8" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/run-deployment-test
        name: "Run deployment test using KinD and Helm"
        with:
          imagename: "edc-controlplane-postgresql-hashicorp-vault edc-dataplane-hashicorp-vault"
          rootDir: "edc-controlplane/edc-controlplane-postgresql-hashicorp-vault edc-dataplane/edc-dataplane-hashicorp-vault"
          k8sversion: ${{ matrix.k8s-version }}
          helm_command: |-
            helm install tx-prod charts/tractusx-connector \
            -f edc-tests/deployment/src/main/resources/helm/tractusx-connector-test.yaml \
            --dependency-update \
            --wait-for-jobs --timeout=120s    

            # wait for the pod to become ready
            kubectl rollout status deployment tx-prod-controlplane
            kubectl rollout status deployment tx-prod-dataplane

            # execute the helm test using token based auth in the Management API
            helm test tx-prod
