name: "KICS"

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v2

      - name: KICS scan
        uses: checkmarx/kics-github-action@master
        with:
          path: "."
          fail_on: high
          disable_secrets: true
          output_path: kicsResults/
          output_formats: "json,sarif"
          exclude_queries: "fd54f200-402c-4333-a5a4-36ef6709af2f,b03a748a-542d-44f4-bb86-9199ab4fd2d5"
          # Excluded queries are:
          # fd54f200-402c-4333-a5a4-36ef6709af2f Missing User Instruction
          # b03a748a-542d-44f4-bb86-9199ab4fd2d5 Healthcheck Instruction Missing

      - name: Upload SARIF file for GitHub Advanced Security Dashboard
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: kicsResults/results.sarif
